#!/usr/bin/env python3
"""Extract selected Endfield UI AssetBundles from the installed VFS.

The script consumes metadata generated by Endfield-Studio:

* Bundle.json / InitBundle.json: decoded metadata for VFS bundle groups
* bundle_manifest_assets.csv: asset path -> AssetBundle mapping

It only reads the game installation. Extracted bundles and selection reports are
written below the requested output directory.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import struct
from pathlib import Path, PurePosixPath
from typing import Iterable


CHACHA_KEY = bytes.fromhex(
    "E95B317AC4F828569D23A86BF271DCB5"
    "3E846FA75C924D671DBA8E38F4CA52E1"
)

DEFAULT_PATTERNS = (
    r"/ui/sprites/(?:itemicon(?:big)?|skillicon|bufficon|monstericon(?:big)?|"
    r"charroundicon|charicon|charremoteicon(?:700)?|charbattleicon|headframeicon|"
    r"playeravatar|wpnattricon|medalicon(?:big)?)/",
    r"business_card",
    r"/ui/sprites/(?:friendlistbg|themeicon/themechangebg)/",
)

# Covers UI textures named as icons, buttons, marks, logos, badges, symbols,
# arrows, keys, tabs, and related glyphs. The profile/mission families are
# included in full because several icon-like glyphs there use deco_* names.
ALL_ICON_PATTERNS = (
    r"^assets/beyond/(?:dynamicassets/gameplay|initialassets|arts(?:/effects)?)/ui/"
    r"(?:(?:.+/)?[^/]*icon[^/]*/.+|(?:.+/)?(?:[^/]*icon[^/]*|(?:btn|mark|"
    r"logo|badge|emblem|symbol|sign|arrow|cursor|pointer|key|tab|tag)_[^/]*))"
    r"\.(?:png|tga|psd)$",
    r"^assets/beyond/(?:dynamicassets/gameplay|arts)/ui/sprites/"
    r"(?:friend|mission|missionicon|mainhud)/.*\.(?:png|tga|psd)$",
    r"^assets/beyond/(?:dynamicassets/gameplay|arts)/ui/sprites/"
    r"(?:charinfo/potential|contingencycontract)/.*\.(?:png|tga|psd)$",
)


def _rotl32(value: int, count: int) -> int:
    return ((value << count) | (value >> (32 - count))) & 0xFFFFFFFF


def _quarter_round(state: list[int], a: int, b: int, c: int, d: int) -> None:
    state[a] = (state[a] + state[b]) & 0xFFFFFFFF
    state[d] = _rotl32(state[d] ^ state[a], 16)
    state[c] = (state[c] + state[d]) & 0xFFFFFFFF
    state[b] = _rotl32(state[b] ^ state[c], 12)
    state[a] = (state[a] + state[b]) & 0xFFFFFFFF
    state[d] = _rotl32(state[d] ^ state[a], 8)
    state[c] = (state[c] + state[d]) & 0xFFFFFFFF
    state[b] = _rotl32(state[b] ^ state[c], 7)


def _chacha20_block(key: bytes, nonce: bytes, counter: int) -> bytes:
    if len(key) != 32 or len(nonce) != 12:
        raise ValueError("ChaCha20 requires a 32-byte key and 12-byte nonce")

    initial = list(struct.unpack("<4I", b"expand 32-byte k"))
    initial.extend(struct.unpack("<8I", key))
    initial.append(counter & 0xFFFFFFFF)
    initial.extend(struct.unpack("<3I", nonce))
    working = initial.copy()
    for _ in range(10):
        _quarter_round(working, 0, 4, 8, 12)
        _quarter_round(working, 1, 5, 9, 13)
        _quarter_round(working, 2, 6, 10, 14)
        _quarter_round(working, 3, 7, 11, 15)
        _quarter_round(working, 0, 5, 10, 15)
        _quarter_round(working, 1, 6, 11, 12)
        _quarter_round(working, 2, 7, 8, 13)
        _quarter_round(working, 3, 4, 9, 14)

    return struct.pack(
        "<16I", *((working[index] + initial[index]) & 0xFFFFFFFF for index in range(16))
    )


def chacha20_xor(data: bytes, key: bytes, nonce: bytes, counter: int = 1) -> bytes:
    output = bytearray(len(data))
    for offset in range(0, len(data), 64):
        stream = _chacha20_block(key, nonce, counter)
        block = data[offset : offset + 64]
        output[offset : offset + len(block)] = bytes(
            value ^ stream[index] for index, value in enumerate(block)
        )
        counter = (counter + 1) & 0xFFFFFFFF
    return bytes(output)


def load_bundle_entries(bundle_jsons: Iterable[Path]) -> dict[str, dict]:
    entries: dict[str, dict] = {}
    for bundle_json in bundle_jsons:
        payload = json.loads(bundle_json.read_text(encoding="utf-8"))
        version = int(payload["Version"])
        group_hash = str(payload["GroupCfgHashName"])
        for chunk in payload["AllChunks"]:
            for source_item in chunk["Files"]:
                item = source_item.copy()
                virtual_name = item["FileName"].replace("\\", "/")
                prefix = "Data/Bundles/Windows/"
                if virtual_name.lower().startswith(prefix.lower()):
                    virtual_name = virtual_name[len(prefix) :]
                item["_vfs_group_hash"] = group_hash
                item["_version"] = version
                entries[virtual_name.lower()] = item
    return entries


def select_assets(
    manifest_csv: Path, patterns: Iterable[str]
) -> tuple[list[dict[str, str]], set[str]]:
    matchers = [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
    selected: list[dict[str, str]] = []
    bundles: set[str] = set()
    with manifest_csv.open("r", encoding="utf-8", newline="") as stream:
        for row in csv.DictReader(stream):
            asset_path = row["asset_path"].replace("\\", "/")
            if not any(pattern.search(asset_path) for pattern in matchers):
                continue
            row["asset_path"] = asset_path
            row["bundle_name"] = row["bundle_name"].replace("\\", "/")
            selected.append(row)
            bundles.add(row["bundle_name"].lower())
    return selected, bundles


def safe_relative_bundle_path(bundle_name: str) -> Path:
    posix = PurePosixPath(bundle_name)
    if posix.is_absolute() or ".." in posix.parts or not posix.parts:
        raise ValueError(f"Unsafe bundle path in manifest: {bundle_name!r}")
    return Path(*posix.parts)


def locate_chunk(game_root: Path, group_hash: str, chunk_id: str) -> Path:
    relative = Path("VFS", group_hash, f"{chunk_id}.chk")
    candidates = (
        game_root / "Endfield_Data" / "Persistent" / relative,
        game_root / "Endfield_Data" / "StreamingAssets" / relative,
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"Chunk not found: {relative}")


def read_bundle(game_root: Path, entry: dict) -> bytes:
    chunk = locate_chunk(
        game_root, entry["_vfs_group_hash"], entry["FileChunkMD5Name"]
    )
    offset = int(entry["Offset"])
    length = int(entry["Len"])
    with chunk.open("rb") as stream:
        stream.seek(offset)
        payload = stream.read(length)
    if len(payload) != length:
        raise EOFError(f"Short read from {chunk}: expected {length}, got {len(payload)}")

    if entry.get("BUseEncrypt"):
        nonce = struct.pack("<iq", entry["_version"], int(entry["IvSeed"]))
        payload = chacha20_xor(payload, CHACHA_KEY, nonce, counter=1)
    return payload


def bundle_file_matches(path: Path, entry: dict) -> bool:
    if not path.is_file() or path.stat().st_size != int(entry["Len"]):
        return False
    expected_md5 = str(entry.get("FileDataMD5") or "").lower()
    if not expected_md5:
        return True
    digest = hashlib.md5()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest() == expected_md5


def write_reports(
    output: Path,
    selected_assets: list[dict[str, str]],
    selected_bundles: list[tuple[str, dict]],
) -> None:
    reports = output / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    with (reports / "selected_assets.csv").open("w", encoding="utf-8", newline="") as stream:
        fields = ("asset_path", "bundle_index", "bundle_name", "asset_size")
        writer = csv.DictWriter(stream, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(selected_assets)

    with (reports / "selected_bundles.csv").open("w", encoding="utf-8", newline="") as stream:
        fields = (
            "bundle_name",
            "vfs_group",
            "chunk_id",
            "offset",
            "length",
            "encrypted",
            "md5",
        )
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        for name, entry in selected_bundles:
            writer.writerow(
                {
                    "bundle_name": name,
                    "vfs_group": entry["_vfs_group_hash"],
                    "chunk_id": entry["FileChunkMD5Name"],
                    "offset": entry["Offset"],
                    "length": entry["Len"],
                    "encrypted": entry["BUseEncrypt"],
                    "md5": entry["FileDataMD5"],
                }
            )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument(
        "--bundle-json",
        type=Path,
        action="append",
        required=True,
        help="Decoded Bundle/InitBundle .blc JSON; repeat for multiple VFS groups.",
    )
    parser.add_argument("--manifest-csv", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--pattern",
        action="append",
        help="Case-insensitive asset-path regex; may be repeated. Defaults to the study UI pack.",
    )
    parser.add_argument(
        "--preset",
        choices=("study-pack", "all-icons"),
        default="study-pack",
        help="Built-in selection used when --pattern is omitted.",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    preset_patterns = ALL_ICON_PATTERNS if args.preset == "all-icons" else DEFAULT_PATTERNS
    patterns = args.pattern or preset_patterns
    entries = load_bundle_entries(args.bundle_json)
    selected_assets, bundle_names = select_assets(args.manifest_csv, patterns)

    selected_bundles: list[tuple[str, dict]] = []
    missing: list[str] = []
    for name in sorted(bundle_names):
        entry = entries.get(name)
        if entry is None:
            missing.append(name)
            continue
        selected_bundles.append((name, entry))

    total_bytes = sum(int(entry["Len"]) for _, entry in selected_bundles)
    print(
        f"Selected assets={len(selected_assets)}, bundles={len(selected_bundles)}, "
        f"bytes={total_bytes} ({total_bytes / 1024 / 1024:.2f} MiB), missing={len(missing)}"
    )
    if missing:
        print("Bundles absent from the Bundle VFS group (usually initial/i18n assets):")
        for name in missing[:20]:
            print(f"  {name}")

    write_reports(args.output, selected_assets, selected_bundles)
    if args.dry_run:
        return 0

    raw_root = args.output / "raw"
    ok = 0
    failed = 0
    for index, (name, entry) in enumerate(selected_bundles, start=1):
        destination = raw_root / safe_relative_bundle_path(name)
        try:
            if destination.is_file() and not args.overwrite:
                if bundle_file_matches(destination, entry):
                    ok += 1
                    continue
            payload = read_bundle(args.game_root, entry)
            expected_md5 = str(entry.get("FileDataMD5") or "").lower()
            actual_md5 = hashlib.md5(payload).hexdigest()
            if expected_md5 and actual_md5 != expected_md5:
                raise ValueError(
                    f"MD5 mismatch for {name}: expected {expected_md5}, got {actual_md5}"
                )
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(payload)
            ok += 1
            if index == 1 or index % 25 == 0 or index == len(selected_bundles):
                print(f"[{index}/{len(selected_bundles)}] extracted {name}")
        except Exception as exc:  # report remaining files instead of aborting a long extraction
            failed += 1
            print(f"[FAIL] {name}: {exc}")

    print(f"Done. extracted/skipped={ok}, failed={failed}, output={raw_root}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
